-- Permisos por acción (catálogo inicial)
INSERT INTO public.permissions (code, module, description) VALUES
  ('company.settings.view', 'company', 'Ver configuración de la empresa'),
  ('company.settings.edit', 'company', 'Modificar configuración de la empresa'),
  ('users.manage', 'security', 'Administrar usuarios y roles'),
  ('cost.view', 'inventory', 'Consultar costos y utilidades'),
  ('price.edit', 'catalog', 'Cambiar precios de venta'),
  ('discount.apply', 'sales', 'Aplicar descuentos en ventas'),
  ('sales.below_cost', 'sales', 'Vender por debajo del costo'),
  ('credit.approve', 'sales', 'Aprobar ventas a crédito'),
  ('inventory.adjust', 'inventory', 'Ajustar inventario'),
  ('inventory.transfer', 'inventory', 'Trasladar entre almacenes'),
  ('purchase.create', 'purchases', 'Crear órdenes y recepciones de compra'),
  ('purchase.post', 'purchases', 'Confirmar compras y facturas de proveedor'),
  ('sales.pos', 'sales', 'Operar punto de venta'),
  ('sales.confirm', 'sales', 'Confirmar ventas y cotizaciones'),
  ('payment.collect', 'treasury', 'Registrar cobros a clientes'),
  ('payment.pay_supplier', 'treasury', 'Registrar pagos a proveedores'),
  ('expense.register', 'treasury', 'Registrar gastos operativos'),
  ('returns.process', 'sales', 'Procesar devoluciones'),
  ('document.reverse', 'accounting', 'Revertir documentos confirmados'),
  ('cash.session.open', 'treasury', 'Abrir sesión de caja'),
  ('cash.session.close', 'treasury', 'Cerrar sesión de caja'),
  ('reports.financial', 'reports', 'Ver reportes financieros'),
  ('reports.operational', 'reports', 'Ver reportes operativos'),
  ('accounting.period.close', 'accounting', 'Cerrar períodos contables'),
  ('accounting.journal.view', 'accounting', 'Ver libro diario y mayor');
